src/objects/MPUID__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>MPUIDS</relationshipLabel>
        <relationshipName>MPUIDS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MPUID</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SMUID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPUIDS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <label>Loan Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPUID__c</fullName>
        <label>MPUID</label>
        <referenceTo>MPUID__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/AP_OpportunityTriggerMP.cls
public with sharing class AP_OpportunityTriggerMP{
   public static void createAutoObject(List<MPUID__c> objList){
  List<Opportunity> oppRecords=new List<Opportunity>();
  insert objList; 
  Set<ID> objIDS= new Set<ID>();
  for(MPUID__c objId:objList)
      objIds.add(objId.id);
      
  for(MPUID__c mpuid: [SELECT name, opportunity__c from MPUID__c where id IN :objIds])
  {
      Opportunity opp=new Opportunity(Id= mpuid.opportunity__c);
      opp.Loan_Number__c= mpuid.name;
      oppRecords.add(opp);
  }
  if(!oppRecords.isEmpty())
      update oppRecords;
  }

}