src/objects/NovaRun__c.object
<CustomObject>
    <description>This object holds NovaCop run information on a project like total lines of code,total violations, date run etc.</description>
    <fields>
        <fullName>DateRun__c</fullName>
        <label>Date Run</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Incident_Measure__c</fullName>
        <label>Incident Measure</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NQI__c</fullName>
        <label>NQI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P1_Records__c</fullName>
        <label>P1 Violations</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P2_Records__c</fullName>
        <label>P2 Violations</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P3_Records__c</fullName>
        <label>P3 Violations</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P4_Records__c</fullName>
        <label>P4 Violations</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>NovaRuns</relationshipLabel>
        <relationshipName>NovaRuns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Violations__c</fullName>
        <label>Total Violations</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_lines_of_code__c</fullName>
        <label>Total lines of code</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NovaRun</label>
    <nameField>
        <label>NovaRun Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NovaRuns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <description>Project End Date</description>
        <inlineHelpText>Project End Date till which Novacop should automatically scan and send the Novacop Dashboard</inlineHelpText>
        <label>Project End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_POC_Contact_Number__c</fullName>
        <label>Project POC Contact Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Project_POC_Email_Id__c</fullName>
        <label>Project POC Email Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_POC_Name__c</fullName>
        <label>Project POC Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Project Start Date</description>
        <inlineHelpText>Project Start Date from which Novacop should automatically scan and send the Novacop Dashboard</inlineHelpText>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NovaSuitePreventController_TEST.cls
@isTest
private class NovaSuitePreventController_TEST {
    static testMethod void testNovaSuitePreventDelete() {
        Project__c testProject = new Project__c();
        testProject.Name = 'Test Project';
        testProject.Project_POC_Name__c = 'Mr. Hunt';
        testProject.Project_POC_Email_Id__c = 'k.narasiman@accenture.com';
        testProject.Project_POC_Contact_Number__c = '+91-8050390430';
        testProject.Project_Start_Date__c = System.today();
        testProject.Project_End_Date__c = System.today()+10;
        Database.insert(testProject);
        
        NovaRun__c run = new NovaRun__c();
        run.P1_Records__c = 10;
        run.P2_Records__c = 20;
        run.P3_Records__c = 30;
        run.P4_Records__c = 40;
        run.NQI__c = 8;
        run.DateRun__c = Date.Today();
        run.Incident_Measure__c = 1;
        run.Total_Violations__c = 1000;
        run.Total_lines_of_code__c = 10000;
        run.Project__c = testProject.id;   
        Database.insert(run); 
        ApexPages.currentPage().getParameters().put('retURL', run.id);
        Test.startTest();
            ApexPages.StandardController controller = new ApexPages.StandardController(run);
            NovaSuitePreventController cont = new NovaSuitePreventController(controller);
            NovaSuitePreventController.preventNovaRunEdit();
            NovaSuitePreventController.preventNovaRunDelete();
        Test.stopTest();
    }
    
    static testMethod void testNovaSuitePrevent() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Novacop Users']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com.novaTest');
                
        Project__c testProject = new Project__c();
        testProject.Name = 'Test Project';
        testProject.Project_POC_Name__c = 'Mr. Hunt';
        testProject.Project_POC_Email_Id__c = 'k.narasiman@accenture.com';
        testProject.Project_POC_Contact_Number__c = '+91-8050390430';
        testProject.Project_Start_Date__c = System.today();
        testProject.Project_End_Date__c = System.today()+10;
        Database.insert(testProject);
        
        NovaRun__c run = new NovaRun__c();
        run.P1_Records__c = 10;
        run.P2_Records__c = 20;
        run.P3_Records__c = 30;
        run.P4_Records__c = 40;
        run.NQI__c = 8;
        run.DateRun__c = Date.Today();
        run.Incident_Measure__c = 1;
        run.Total_Violations__c = 1000;
        run.Total_lines_of_code__c = 10000;
        run.Project__c = testProject.id;   
        Database.insert(run); 
        ApexPages.currentPage().getParameters().put('retURL', run.id);
        System.runAs(u){
            Test.startTest();
                ApexPages.StandardController controller = new ApexPages.StandardController(run);
                NovaSuitePreventController cont = new NovaSuitePreventController(controller);
                NovaSuitePreventController.preventNovaRunEdit();
                NovaSuitePreventController.preventNovaRunDelete();
            Test.stopTest();
        }
    }
}