src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Field Used for Batch Apex</description>
        <label>Opportunity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/StaticStringCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the List of Salesforce Ids or Strings that can be referred in Configuration and Customization</description>
    <fields>
        <fullName>StaticStringValue__c</fullName>
        <description>Stores the static strings or ids to be used in the Apex code</description>
        <inlineHelpText>value to be used</inlineHelpText>
        <label>Static String Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CS001_StaticStrings</label>
</CustomObject>

src/classes/OpportunityStatusBatch.cls
global class OpportunityStatusBatch implements Database.Batchable<sObject> {
/* Variable */
global String query;
/* Constructor */
global OpportunityStatusBatch(String q){
query = q;
}
/* Start Method */
global Database.QueryLocator start(Database.BatchableContext BC){
return Database.getQueryLocator(query);
}
/* Execute Method */
global void execute(Database.BatchableContext BC,List<Opportunity> opp){
List<Opportunity> oppUpdate = new List<Opportunity>();
for(Opportunity oppClose:opp){
if(oppClose.CloseDate < Date.Today()){
oppClose.Opportunity_Status__c = StaticStringCustomSettings__c.getInstance('CL_4').StaticStringValue__c;
oppUpdate.add(oppClose);
}
}
Database.SaveResult[] dmlExResult = Database.update(oppUpdate,false);
for(Database.SaveResult sr : dmlExResult ){
if (!sr.isSuccess()) {
Database.Error err = sr.getErrors()[0];
}
}
}
/* Finish Method */
global void finish(Database.BatchableContext BC){
// Query the AsyncApexJob object to retrieve the current job's information.
AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
TotalJobItems, CreatedBy.Email
FROM AsyncApexJob WHERE Id = :BC.getJobId()];
System.debug('** Batch Job Status ==> '+a);
}
}