src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity External Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StaticStringCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the List of Salesforce Ids or Strings that can be referred in Configuration and Customization</description>
    <fields>
        <fullName>StaticStringValue__c</fullName>
        <description>Stores the static strings or ids to be used in the Apex code</description>
        <inlineHelpText>value to be used</inlineHelpText>
        <label>Static String Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CS001_StaticStrings</label>
</CustomObject>

src/classes/AP_OpportunityTrigger_Test.cls
@isTest
public class AP_OpportunityTrigger_Test
{
static testmethod void matchOpportunityTest()
{
//Opportunity opp = new Opportunity(StageName=StaticStringCustomSettings__c.getInstance('CL_4').StaticStringValue__c,CloseDate = Date.Today(),Name =StaticStringCustomSettings__c.getInstance('CL_7').StaticStringValue__c,Opportunity_External_Id__c =StaticStringCustomSettings__c.getInstance('CL_23').StaticStringValue__c,OrderNumber__c =StaticStringCustomSettings__c.getInstance('CL_24').StaticStringValue__c,TrackingNumber__c =StaticStringCustomSettings__c.getInstance('CL_24').StaticStringValue__c);
Opportunity opp = new Opportunity(StageName = 'Confirm Interest',closedate = Date.today(),Name = 'Confirm Interest - Opp');
insert opp;

//Opportunity oppMatch = new Opportunity(StageName=StaticStringCustomSettings__c.getInstance('CL_4').StaticStringValue__c,CloseDate = Date.Today(),Name =StaticStringCustomSettings__c.getInstance('CL_7').StaticStringValue__c,Opportunity_External_Id__c =StaticStringCustomSettings__c.getInstance('CL_23').StaticStringValue__c,OrderNumber__c = StaticStringCustomSettings__c.getInstance('CL_25').StaticStringValue__c,TrackingNumber__c =StaticStringCustomSettings__c.getInstance('CL_25').StaticStringValue__c);
Opportunity oppMatch = new Opportunity(StageName = 'Confirm Interest',closedate = Date.today(),Name = 'Confirm Interest - OppMatch');
insert oppMatch;

try
{
oppMatch.AccountId = Userinfo.getuserid();
update oppMatch;
}catch(Exception exp){}
}

}