src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password to access Novacop project</description>
        <inlineHelpText>Password to access Novacop project</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <description>Project End Date</description>
        <inlineHelpText>Project End Date till which Novacop should automatically scan and send the Novacop Dashboard</inlineHelpText>
        <label>Project End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_POC_Contact_Number__c</fullName>
        <label>Project POC Contact Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Project_POC_Email_Id__c</fullName>
        <label>Project POC Email Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_POC_Name__c</fullName>
        <label>Project POC Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Token__c</fullName>
        <inlineHelpText>Salesforce.com security token to access this org through a third party application</inlineHelpText>
        <label>Security Token</label>
        <length>25</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>User Name to access the Novacop project</description>
        <inlineHelpText>User Name to access the Novacop project</inlineHelpText>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProjectSubmitForApproval_Test.cls
@isTest
private class ProjectSubmitForApproval_Test{
    private static List<Project__c> projectList = new List<Project__c>();
    
    static List<Project__c> createTestData(Integer size){
        List<Project__c> projList = new List<Project__c>();
            for(integer i = 1; i <= size; i++) {
            Project__c projObj = new Project__c();
                projObj.Name = 'TestProject';
                projObj.User_Name__c = 'test@test.com';
                projObj.Project_POC_Contact_Number__c = '99998888889';
                projObj.Project_POC_Email_Id__c = 'testPoc@test.com';
                projObj.Project_POC_Name__c = 'testPOC';
                projObj.Password__c = 'testPassword';
                projObj.Security_Token__c = 'AEJU4hMeWuw4YLZl262bFwKNA';
                projObj.Project_End_Date__c = Date.Today() +30;
                projList.add(projObj);
        }
        return projList;
    } 
    
    static testMethod void afterInsertProject(){
        projectList = createTestData(5);
        Database.insert(projectList);
    }
}