src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <description>Project End Date</description>
        <inlineHelpText>Project End Date till which Novacop should automatically scan and send the Novacop Dashboard</inlineHelpText>
        <label>Project End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_POC_Contact_Number__c</fullName>
        <label>Project POC Contact Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Project_POC_Email_Id__c</fullName>
        <label>Project POC Email Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_POC_Name__c</fullName>
        <label>Project POC Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Project Start Date</description>
        <inlineHelpText>Project Start Date from which Novacop should automatically scan and send the Novacop Dashboard</inlineHelpText>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NovaSuiteLastScanController_TEST.cls
@isTest
private class NovaSuiteLastScanController_TEST {

    static testMethod void testNovaSuiteLastScan() {
        Project__c testProject = new Project__c();
        testProject.Name = 'Test Project';
        testProject.Project_POC_Name__c = 'Mr. Hunt';
        testProject.Project_POC_Email_Id__c = 'k.narasiman@accenture.com';
        testProject.Project_POC_Contact_Number__c = '+91-8050390430';
        testProject.Project_Start_Date__c = System.today();
        testProject.Project_End_Date__c = System.today()+10;
        Database.insert(testProject);
        
        Test.startTest();
            NovaSuiteLastScanController ctr = new NovaSuiteLastScanController();
            System.assert(!ctr.projectList.isEmpty());
            System.assertEquals(1, ctr.projectList.size());    
        Test.stopTest();
    }
    
}