src/objects/Snippet__c.object
<CustomObject>
    <fields>
        <fullName>EffortSaving__c</fullName>
        <label>Effort Saving (mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SnippetId__c</fullName>
        <label>Snippet Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Snippy__c</fullName>
        <label>Snippy</label>
        <referenceTo>Snippy__c</referenceTo>
        <relationshipLabel>Snippets</relationshipLabel>
        <relationshipName>Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Snippet</label>
    <nameField>
        <displayFormat>SNP-{0000}</displayFormat>
        <label>Snippets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Snippy__c.object
<CustomObject>
    <label>Snippy</label>
    <nameField>
        <label>Snippy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Snippy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SnippyEffortSaving__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EffortSaving__c</fullName>
        <label>Effort Saving</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Snippy</label>
</CustomObject>

src/classes/Snippy_Test.cls
@isTest
private class Snippy_Test {
     static testMethod void newSnippets() {
         
     
         Snippy__c snp = new Snippy__c(Name = 'Snippy');
         Database.insert(snp);
         
         Set<String> snippetIds = new Set<String>{'Insert','Update','UpsertWithoutExternalId',
                                                  'UpsertWithExternalId','Delete','UnDelete'};
         
         List<SnippyEffortSaving__c > csList = new List<SnippyEffortSaving__c >();
         for(String str : snippetIds){
             SnippyEffortSaving__c cs = new SnippyEffortSaving__c(Name = str, EffortSaving__c = 10);
             csList.add(cs);
         }
         Database.insert(csList);
         
         List<Snippet__c > snippetsList = new List<Snippet__c>();                                         
         for(String str : snippetIds){
             Snippet__c snpt = new Snippet__c(SnippetId__c = str, Snippy__c = snp.id);
             snippetsList.add(snpt);
         } 
         
         Database.insert(snippetsList);
     }
}